site_name: SKILSTAK UNIX/Linux Beginner Boost
site_url: https://rwxrob.github.io/boost
repo_url: https://github.com/rwxrob/boost
dev_addr: '0.0.0.0:8000'

theme:
  name: material
  font:
    text: Work Sans
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


